-- ================================================================
-- 20260929000002_site_content_seed.sql: seed every editable string
-- ================================================================
-- GENERATED by scripts/gen-site-content-seed.mjs from
-- src/lib/site-content-defaults.ts. Do not edit by hand.
--
-- Values are the copy currently on the staging frontend, so applying
-- this changes nothing visually. ON CONFLICT DO NOTHING: re-running
-- never overwrites copy the club has since edited.
--
-- 67 keys across 7 admin tabs.
-- ================================================================

INSERT INTO public.site_content
  (key, value, kind, max_length, page, section, label, help, display_order)
VALUES
  ('home.hero.title_line1', 'Welcome to', 'text', 24, 'Home', 'Hero', 'Greeting', 'The smaller line above the club name.', 10),
  ('home.hero.title_line2', 'Western’s', 'text', 14, 'Home', 'Hero', 'Name, line 1', 'Each name line is set very large, so keep it to one or two words.', 20),
  ('home.hero.title_line3', 'Sales', 'text', 14, 'Home', 'Hero', 'Name, line 2', NULL, 30),
  ('home.hero.title_line4', 'Community', 'text', 14, 'Home', 'Hero', 'Name, line 3', NULL, 40),
  ('home.hero.subtitle', 'A student-run sales organization at Western University.', 'text', 90, 'Home', 'Hero', 'Subtitle', NULL, 50),
  ('home.hero.button_label', 'Apply to join', 'text', 28, 'Home', 'Hero', 'Button text', NULL, 60),
  ('home.hero.button_href', 'https://westernusc.store/product/western-sales-club/', 'url', 200, 'Home', 'Hero', 'Button link', NULL, 70),
  ('home.about.eyebrow', 'About', 'text', 24, 'Home', 'About', 'Eyebrow', NULL, 80),
  ('home.about.title_line1', 'A sales floor', 'text', 24, 'Home', 'About', 'Heading, line 1', NULL, 90),
  ('home.about.title_line2', 'run by students', 'text', 24, 'Home', 'About', 'Heading, line 2', 'Leave empty for a one-line heading.', 100),
  ('home.about.body', 'Western Sales Club is a student-run organization at Western University. We run workshops and events through the year, and connect members with people who sell for a living.', 'longtext', 320, 'Home', 'About', 'Body copy', NULL, 110),
  ('home.about.link_label', 'Learn about the club', 'text', 28, 'Home', 'About', 'Link text', 'The arrow is added automatically.', 120),
  ('home.events.eyebrow', 'Events', 'text', 24, 'Home', 'Events', 'Eyebrow', NULL, 130),
  ('home.events.title_line1', 'On the', 'text', 24, 'Home', 'Events', 'Heading, line 1', NULL, 140),
  ('home.events.title_line2', 'calendar', 'text', 24, 'Home', 'Events', 'Heading, line 2', 'Leave empty for a one-line heading.', 150),
  ('home.events.empty', 'No events on the calendar yet.', 'text', 60, 'Home', 'Events', 'Empty message', 'Shown when nothing is published.', 160),
  ('home.events.link_label', 'See all events', 'text', 28, 'Home', 'Events', 'Link text', NULL, 170),
  ('home.partners.eyebrow', 'Partners', 'text', 24, 'Home', 'Partners', 'Eyebrow', NULL, 180),
  ('home.partners.title_line1', 'Who we work with', 'text', 24, 'Home', 'Partners', 'Heading', NULL, 190),
  ('home.partners.link_label', 'See all partners', 'text', 28, 'Home', 'Partners', 'Link text', NULL, 200),
  ('home.contact.eyebrow', 'Contact', 'text', 24, 'Home', 'Contact', 'Eyebrow', NULL, 210),
  ('home.contact.title_line1', 'Get in touch', 'text', 24, 'Home', 'Contact', 'Heading', NULL, 220),
  ('home.contact.body', 'Reach out about partnerships, speaking at an event, or joining the club.', 'longtext', 200, 'Home', 'Contact', 'Body copy', NULL, 230),
  ('home.contact.link_label', 'Contact us', 'text', 28, 'Home', 'Contact', 'Button text', NULL, 240),
  ('home.cta.eyebrow', 'Join', 'text', 24, 'Home', 'Join', 'Eyebrow', NULL, 250),
  ('home.cta.title_line1', 'Apply to join', 'text', 24, 'Home', 'Join', 'Heading', NULL, 260),
  ('home.cta.subtitle', 'Membership is sold through the Western USC store.', 'text', 90, 'Home', 'Join', 'Subtitle', NULL, 270),
  ('home.cta.button_label', 'Apply to join', 'text', 28, 'Home', 'Join', 'Button text', NULL, 280),
  ('home.cta.button_href', 'https://westernusc.store/product/western-sales-club/', 'url', 200, 'Home', 'Join', 'Button link', NULL, 290),
  ('about.header.eyebrow', 'About', 'text', 24, 'About', 'Header', 'Eyebrow', NULL, 300),
  ('about.header.title', 'What Western Sales Club does.', 'text', 60, 'About', 'Header', 'Page title', NULL, 310),
  ('about.story.fact1_eyebrow', 'What we do', 'text', 24, 'About', 'Fact 1', 'Eyebrow', NULL, 320),
  ('about.story.fact1_title', 'Workshops and events, all year', 'text', 48, 'About', 'Fact 1', 'Heading', NULL, 330),
  ('about.story.fact1_body1', 'Western Sales Club runs workshops and events through the year for students who want experience in sales before they graduate.', 'longtext', 220, 'About', 'Fact 1', 'First paragraph', NULL, 340),
  ('about.story.fact1_body2', 'Members learn from people who do the work, not only from a reading list.', 'longtext', 220, 'About', 'Fact 1', 'Second paragraph', 'Leave empty to hide.', 350),
  ('about.story.fact2_eyebrow', 'How we run', 'text', 24, 'About', 'Fact 2', 'Eyebrow', NULL, 360),
  ('about.story.fact2_title', 'A student exec team', 'text', 48, 'About', 'Fact 2', 'Heading', NULL, 370),
  ('about.story.fact2_body1', 'Presidents, vice presidents, and assistant vice presidents run the club.', 'longtext', 220, 'About', 'Fact 2', 'First paragraph', NULL, 380),
  ('about.story.fact2_body2', 'The roster is on the executive team page, and it turns over every year.', 'longtext', 220, 'About', 'Fact 2', 'Second paragraph', 'Leave empty to hide.', 390),
  ('about.story.fact3_eyebrow', 'Who backs us', 'text', 24, 'About', 'Fact 3', 'Eyebrow', NULL, 400),
  ('about.story.fact3_title', 'Five industry partners', 'text', 48, 'About', 'Fact 3', 'Heading', NULL, 410),
  ('about.story.fact3_body1', 'Partners support the club and connect members with people working in the field.', 'longtext', 220, 'About', 'Fact 3', 'First paragraph', NULL, 420),
  ('about.story.fact3_body2', 'They are listed on the partners page.', 'longtext', 220, 'About', 'Fact 3', 'Second paragraph', 'Leave empty to hide.', 430),
  ('about.story.fact4_eyebrow', 'How to join', 'text', 24, 'About', 'Fact 4', 'Eyebrow', NULL, 440),
  ('about.story.fact4_title', 'Membership runs through the USC store', 'text', 48, 'About', 'Fact 4', 'Heading', NULL, 450),
  ('about.story.fact4_body1', 'The club runs about ten events a year for its members.', 'longtext', 220, 'About', 'Fact 4', 'First paragraph', NULL, 460),
  ('about.story.fact4_body2', 'Questions go to sales.club@westernusc.ca.', 'longtext', 220, 'About', 'Fact 4', 'Second paragraph', 'Leave empty to hide.', 470),
  ('team.header.eyebrow', 'Team', 'text', 24, 'Team', 'Header', 'Eyebrow', NULL, 480),
  ('team.header.title_line1', 'Meet our', 'text', 24, 'Team', 'Header', 'Heading, line 1', NULL, 490),
  ('team.header.title_line2', 'executive team', 'text', 24, 'Team', 'Header', 'Heading, line 2', 'Leave empty for a one-line heading.', 500),
  ('team.header.empty', 'No executives are published yet.', 'text', 60, 'Team', 'Header', 'Empty message', NULL, 510),
  ('events.header.eyebrow', 'Events', 'text', 24, 'Events', 'Header', 'Eyebrow', NULL, 520),
  ('events.header.title_line1', 'What we run', 'text', 24, 'Events', 'Header', 'Heading', NULL, 530),
  ('events.header.empty', 'No events are on the calendar yet.', 'text', 60, 'Events', 'Header', 'Empty message', NULL, 540),
  ('partners.header.eyebrow', 'Partners', 'text', 24, 'Partners', 'Header', 'Eyebrow', NULL, 550),
  ('partners.header.title', 'The businesses that support Western Sales Club.', 'text', 60, 'Partners', 'Header', 'Page title', NULL, 560),
  ('partners.wall.label', 'Partners', 'text', 24, 'Partners', 'Logo wall', 'Label', NULL, 570),
  ('partners.wall.empty', 'No partners listed yet.', 'text', 60, 'Partners', 'Logo wall', 'Empty message', NULL, 580),
  ('contact.header.eyebrow', 'Contact', 'text', 24, 'Contact', 'Header', 'Eyebrow', NULL, 590),
  ('contact.header.title', 'Get in touch.', 'text', 60, 'Contact', 'Header', 'Page title', NULL, 600),
  ('contact.header.body', 'Questions about membership, events, or partnerships. You can also email sales.club@westernusc.ca.', 'longtext', 240, 'Contact', 'Header', 'Intro', NULL, 610),
  ('contact.form.submit_label', 'Send message', 'text', 28, 'Contact', 'Form', 'Send button', NULL, 620),
  ('contact.form.sent_title', 'Message sent', 'text', 40, 'Contact', 'Form', 'Sent heading', NULL, 630),
  ('contact.form.sent_body', 'It went to sales.club@westernusc.ca.', 'text', 90, 'Contact', 'Form', 'Sent message', NULL, 640),
  ('footer.contact.email', 'sales.club@westernusc.ca', 'email', 80, 'Footer', 'Contact', 'Email address', NULL, 650),
  ('footer.social.instagram_url', 'https://www.instagram.com/westernsalesclub/', 'url', 200, 'Footer', 'Social', 'Instagram link', 'Leave empty to hide the icon.', 660),
  ('footer.social.linkedin_url', 'https://www.linkedin.com/company/western-sales-club/', 'url', 200, 'Footer', 'Social', 'LinkedIn link', 'Leave empty to hide the icon.', 670)
ON CONFLICT (key) DO NOTHING;


-- ----------------------------------------------------------------
-- SEED STATS: the three figures in the home About slab.
-- Only seeds when the table is empty, so it never resurrects stats
-- the club has deliberately deleted.
-- ----------------------------------------------------------------
INSERT INTO public.site_stats (value, suffix, label, visible, display_order)
SELECT * FROM (VALUES
  (150, '+', 'Members',           true, 10),
  (10,  '+', 'Annual events',     true, 20),
  (5,   '+', 'Industry partners', true, 30)
) AS seed(value, suffix, label, visible, display_order)
WHERE NOT EXISTS (SELECT 1 FROM public.site_stats);
